server:
  port: 8080

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: aircraft
              uri: lb://AIRCRAFT-SERVICE
              predicates:
                - Path=/api/aircraft/**
            - id: flight
              uri: lb://FLIGHT-SERVICE
              predicates:
                - Path=/api/flights/**

eureka:
  client:
    service-url:
      defaultZone: http://naming-service:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
